version: 2
jobs:
  bobby:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "Double trouble"
  workflows:
    version: 2
    bobby_sally:
      jobs:
        - bobby
        - sally